### ISSUE TITLE
Setting looping at runtime

### ISSUE THREAD

**Issue by Ornolfr** [Piasy/RxAndroidAudio#13]
There is not any availability to set looping at runtime. Could you improve this?

**Comment by Piasy** [comment]
Yes we may want to quit looping but not stop play immediately. Your pr is welcome :) 

But please contribute to the `1.2.x` branch.

**Comment by Ornolfr** [comment]
@Piasy hey actually I've got some grasp on this problem, could you check this kind of solution?

```
private void play() {
        player.play(PlayConfig.file(looping ? songsQueue.peek() : songsQueue.poll())
                .looping(looping).leftVolume(1.0f).rightVolume(1.0f).build())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Action1<Boolean>() {
                    @Override
                    public void call(Boolean aBoolean) {
                        play();
                    }
                }, new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        throwable.printStackTrace();
                    }
                });
    }
```

So, if looping was somewhere set to true, then queue is not going further, and replays its head. Am I doing it right? Cannot test right now, just designing my Service for music playback.

**Comment by Piasy** [comment]
That's right.

This library hasn't consider to meet the need of  music player, so we may need add several functionalities into it.

**Comment by Piasy** [comment]
Going to close it, feel free to reopen :)
