### ISSUE TITLE
monitor play status

### ISSUE THREAD

**Issue by milayihe** [Piasy/RxAndroidAudio#14]
How to get the play finish status?

**Comment by Piasy** [comment]
If you read the README carefully, you can see:

``` java
mRxAudioPlayer.play(PlayConfig.file(audioFile).looping(true).build())
        .subscribeOn(Schedulers.io())
        .subscribe(new Action1<Boolean>() {
            @Override
            public void call(Boolean aBoolean) {
                // play finished
                // NOTE: if looping, the Single will never finish, you need stop playing
                // onDestroy, otherwise, memory leak will happen!
            }
        });
```

**Comment by milayihe** [comment]
@Piasy but I found .subscribe() just monitor the start, And .doOnCompleted() monitor the finish status.That's right????

**Comment by Piasy** [comment]
How do you find it out? When the play is finished, the returned `Single` will get a `onSuccess` event.

**Comment by milayihe** [comment]
I tracked your code, found .doOnCompleted() method useful for me .

**Comment by Piasy** [comment]
The `RxAudioPlayer.play` will return a `Single` object, it will emit an `onSuccess` event when the playing is finished.

How do you use the returned `Single` object is totally free to you :)

**Comment by milayihe** [comment]
Tks a lot
