### ISSUE TITLE
Multiple Sounds at once

### ISSUE THREAD

**Issue by Frank1234** [Piasy/RxAndroidAudio#15]
Is it possible to play multiple sounds at once (music and sound effects)?

I see that the play function calls stopPlay(); and the RxAudioPlayer is a singleton, so I'm afraid not?

**Comment by Piasy** [comment]
Yes, it's not supported now.

**Comment by Frank1234** [comment]
Removing the singleton and thereby enabling the use of two RxAudioPlayer objects, one for music and one for sound effects, would that work?

**Comment by Piasy** [comment]
This is not the designed scenario for this library. And to play multiple sounds at the same time, I think they should be played in different session? Sorry that I haven't dive into this level, so I can't answer it clearly.

**Comment by Frank1234** [comment]
Okay, I'll use regular media player for the music.

**Comment by Piasy** [comment]
Going to close it, feel free to reopen :)
