### ISSUE TITLE
It seems not easy to pause and restart.

### ISSUE THREAD

**Issue by liyiheng** [Piasy/RxAndroidAudio#17]
I tried mRxAudioPlayer.getMediaPlayer().pause();

**Comment by Piasy** [comment]
What's the problem here? `mRxAudioPlayer.getMediaPlayer().pause()` and `mRxAudioPlayer.getMediaPlayer().start()` not work?

**Comment by liyiheng** [comment]
It works.

**Comment by liyiheng** [comment]
But how can I pause when recording

**Comment by liyiheng** [comment]
A subclass extands AudioRecorder ?

**Comment by Piasy** [comment]
It didn't cover such use case, you can add a method `getAudioRecorder` like `RxAudioPlayer. getMediaPlayer()`.

Welcome to open a PR :)

**Comment by liyiheng** [comment]
I'm glad to open a PR, but getAudioRecorder() is not a big help.
pause() is available form api24，it means that I have to concat several audio files to implement pause function on lower apis. 
It would be easy for amr format audios, but there are several formats.

**Comment by Piasy** [comment]
So it's limited by Android API, I think audio file concatenation is unavoidable.
