### ISSUE TITLE
Is there any callback to retrieve current amplitude while recording?

### ISSUE THREAD

**Issue by jaychang0917** [Piasy/RxAndroidAudio#23]
Hi, is there any callback to retrieve current amplitude while recording?

Thanks!

**Comment by Piasy** [comment]
See there https://github.com/Piasy/RxAndroidAudio/blob/1.2.x/app/src/main/java/com/github/piasy/rxandroidaudio/example/FileActivity.java#L269

**Comment by jaychang0917** [comment]
Thanks very much!

**Comment by jaychang0917** [comment]
I notify that the max amplitude is 15, any intention for this value?

**Comment by Piasy** [comment]
Just an arbitrary value.
