### ISSUE TITLE
StreamAudioRecord recording format

### ISSUE THREAD

**Issue by WooYu** [Piasy/RxAndroidAudio#32]
mOutputFile = new File(Environment.getExternalStorageDirectory().getAbsolutePath() +
                    File.separator + System.nanoTime() + ".stream.m4a");

Using StreamAudioRecord audio recording, the format is no practical significance.Because there is no converting PCM flow into the corresponding code format.

**Comment by Piasy** [comment]
Sorry that I don't understand what do you mean 😂

**Comment by WooYu** [comment]
Use StreamAudioRecord recording of data is the flow of PCM.Though the output path here is: m4a format, but the file is saved in PCM data streams

**Comment by WooYu** [comment]
There is another problem，AndroidTrack play no Mediaplay's sound loudly

**Comment by Piasy** [comment]
You are right, you can use any file name for the saved file, but the content is in PCM format.

**Comment by WooYu** [comment]
@Piasy Why AndroidTrack play no Mediaplay's sound loudly?

**Comment by Piasy** [comment]
@WooYu Sorry for the late response, I haven't dig into that, maybe you can try to find out the reason :)

**Comment by nikitoSha** [comment]
@Piasy can you show, how to set correct params? After recording, file size very big. For 1 minute - about 10 Mb.

We try this:

          mStreamAudioRecorder.start(
                                44100, AudioFormat.CHANNEL_IN_STEREO,
                                MediaRecorder.OutputFormat.AMR_WB, 4096,
                                new StreamAudioRecorder.AudioDataCallback() {
                                    @Override
                                    public void onAudioData(byte[] data, int size) {
                                        if (mFileOutputStream != null && !pause) {
                                            try {
                                                mFileOutputStream.write(data, 0, size);
                                            } catch (IOException e) {
                                                LogHelper.error(VoiceRecordHelper.class, e.getMessage());
                                            }
                                        }
                                    }

                                    @Override
                                    public void onError() {

                                    }
                                });

But file size now = 44 b. How to minimize output file size?
Compress after recording?
