### ISSUE TITLE
jdk error  your version 1.5.2!!!!!!!!!!!! but 1.5.1 is ok

### ISSUE THREAD

**Issue by gsp0423** [Piasy/RxAndroidAudio#42]
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by gsp0423** [comment]
compile 'com.github.piasy:AudioProcessor:1.5.2'  can't be added,please tell me why!!!!

**Comment by Piasy** [comment]
Use Java 8, or stick on 1.5.1.
