### ISSUE TITLE
依赖库导入失败

### ISSUE THREAD

**Issue by WooYu** [Piasy/RxAndroidAudio#48]
Error:Unable to resolve dependency for ':musicplayer@debugAndroidTest/compileClasspath': Could not resolve com.github.piasy:AudioProcessor:1.5.2.
<a href="openFile:F:/KGe/Karaok/Branch_JapanSDK2/musicplayer/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:musicplayer@debugAndroidTest/compileClasspath&#39;: Could not resolve com.github.piasy:AudioProcessor:1.5.2.">Show Details</a>

**Comment by Piasy** [comment]
加了这个吗？

``` gradle
allprojects {
    repositories {
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
    }
}
```

**Comment by WooYu** [comment]
加了发自我的iPhone------------------ 原始邮件 ------------------发件人: Piasy  <notifications@github.com>发送时间: 2018年2月9日 20:52收件人: Piasy/RxAndroidAudio <RxAndroidAudio@noreply.github.com>抄送: Rain <mr_woo@yeah.net>, Author <author@noreply.github.com>主题: 回复：[Piasy/RxAndroidAudio] 依赖库导入失败 (#48)加了这个吗？
allprojects {
    repositories {
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
    }
}

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Piasy/RxAndroidAudio","title":"Piasy/RxAndroidAudio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Piasy/RxAndroidAudio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Piasy in #48: 加了这个吗？\r\n\r\n``` gradle\r\nallprojects {\r\n    repositories {\r\n        maven {\r\n            url  \"http://dl.bintray.com/piasy/maven\"\r\n        }\r\n    }\r\n}\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/Piasy/RxAndroidAudio/issues/48#issuecomment-364425582"}}}

**Comment by WooYu** [comment]
加了的。maven库中下载jar也失败了。会不会存在类似资源过期的情况。半年前可以正常使用。感觉这项目挺好的，现在用报错了。发自我的iPhone------------------ 原始邮件 ------------------发件人: Piasy  <notifications@github.com>发送时间: 2018年2月9日 20:52收件人: Piasy/RxAndroidAudio <RxAndroidAudio@noreply.github.com>抄送: Rain <mr_woo@yeah.net>, Author <author@noreply.github.com>主题: 回复：[Piasy/RxAndroidAudio] 依赖库导入失败 (#48)加了这个吗？
allprojects {
    repositories {
        maven {
            url  "http://dl.bintray.com/piasy/maven"
        }
    }
}

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Piasy/RxAndroidAudio","title":"Piasy/RxAndroidAudio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Piasy/RxAndroidAudio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Piasy in #48: 加了这个吗？\r\n\r\n``` gradle\r\nallprojects {\r\n    repositories {\r\n        maven {\r\n            url  \"http://dl.bintray.com/piasy/maven\"\r\n        }\r\n    }\r\n}\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/Piasy/RxAndroidAudio/issues/48#issuecomment-364425582"}}}

**Comment by Piasy** [comment]
放在 allprojects 的第一个了吗？

**Comment by WooYu** [comment]
放在第一行也没解决

**Comment by Piasy** [comment]
那这就麻烦了 :(

**Comment by jaychang0917** [comment]
試試在`gradle.properties`加上`android.enableD8=true`

**Comment by mingdroid** [comment]
放在 allprojects 的第一个，好用哦，要不老是从 jitpack.io 加载的
