### ISSUE TITLE
Getting this Error:com.android.builder.dexing.DexArchiveBuilderException

### ISSUE THREAD

**Issue by momersaleem** [Piasy/RxAndroidAudio#49]
Hi, 

I have perfectly updated build.gradle files and synced. But when I try to run project, AS gives me the following error. 

Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\mg\.gradle\caches\transforms-1\files-1.1\rxandroidaudio-1.5.2.aar\e0db6c447c821a62faae95c5f5d73dc7\jars\classes.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/github/piasy/rxandroidaudio/RxAudioPlayer.class
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\mg\.gradle\caches\transforms-1\files-1.1\rxandroidaudio-1.5.2.aar\e0db6c447c821a62faae95c5f5d73dc7\jars\classes.jar

My project settings details:
Gradle version: 4.1
Android plugin version: 3.0.1
Compile Sdk version: API 26 
minSdkVersion 15
targetSdkVersion 26

Please help me to get rid of this error so that I can move on.

Thanks,
momersaleem

**Comment by Piasy** [comment]
Could you please enable Java 8 support in your project setting?

**Comment by momersaleem** [comment]
Thanks, it's done with Java 8 support.
