### ISSUE TITLE
Poor quality in FileActivity

### ISSUE THREAD

**Issue by BackPackerDz** [Piasy/RxAndroidAudio#5]
Hi, thank you for this library but when I tested the demo, the sound quality is very poor in FileActivity 
compared to StreamActivity, it's normal ?

**Comment by Piasy** [comment]
Maybe it's due to the difference of audio record config, I'll give some investigation into it.

**Comment by Piasy** [comment]
@BackPackerDz Hi, after several test, I find out that if I use high sample rate and encoding bit rate when I use `MediaRecorder` to record the audio (`FileActivity`), the sound quality will be improved a lot, and it's nearly the same as the audio recorded using `AudioRecord` (`StreamActivity`).

Try the updated demo.

**Comment by BackPackerDz** [comment]
@Piasy I tested and it's AMAZING, now it's better than Stream Mode ! thank you !

**Comment by qadir-genetech** [comment]
Code?

I have used this.
```
mAudioRecorder = AudioRecorder.getInstance();
mAudioFile = new File(
        Environment.getExternalStorageDirectory().getAbsolutePath() +
                File.separator + System.nanoTime() + ".file.m4a");
mAudioRecorder.prepareRecord(MediaRecorder.AudioSource.MIC,
        MediaRecorder.OutputFormat.MPEG_4, MediaRecorder.AudioEncoder.AAC,
        mAudioFile);
mAudioRecorder.startRecord();
```

audio quality is very poor. 

What to change here in my code.

**Comment by Piasy** [comment]
> use high sample rate and encoding bit rate

**Comment by qadir-genetech** [comment]
@Piasy yes but how? I don't know how to do that

**Comment by Piasy** [comment]
Please RTFSC :)
