### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by desuto** [Piasy/RxAndroidAudio#51]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by Piasy** [comment]
Cool! PR is welcome!

**Comment by desuto** [comment]
what is the point of RX ?

**Comment by Piasy** [comment]
pull request

**Comment by desuto** [comment]
Hi, I have designed it, how do you think? what do you think the number you like?
![rxandroidaudio](https://user-images.githubusercontent.com/39637790/40577958-8fe4d502-6136-11e8-93ff-463513e265c5.png)

**Comment by Piasy** [comment]
I prefer 6 :)

**Comment by desuto** [comment]
Hi @Piasy I have uploaded all the files. You can get it in the link below
https://drive.google.com/drive/folders/1Wij4XZz0ahtTL6PEsaA9RWvWDAmROfFF

**Comment by desuto** [comment]
I've uploaded a different icon size. should I add the folder to the project?

https://drive.google.com/drive/folders/1iroGiruqf_oPPLzejPWvnjLJx1kzLlwK

**Comment by Piasy** [comment]
I'll add it into project later :)

**Comment by desuto** [comment]
ok. I will wait for Pull requests

**Comment by Piasy** [comment]
It's done! Thank you for your contribution!

**Comment by Piasy** [comment]
@desuto Hi, I've another awesome library: https://github.com/Piasy/AudioMixer , could you please design an icon for it? thanks!
