### ISSUE TITLE
Not able to play audio outide app environment 

### ISSUE THREAD

**Issue by saurabh-chhabra** [Piasy/RxAndroidAudio#65]
While recording stream internally , app is playing audio fine but ,while playing same audio from any other player it is not playing the audio !! :(
Any reason why ?

**Comment by Piasy** [comment]
Usually you can play multiple things at the same time, not sure what's your cause, maybe you can provide some error log?

**Comment by saurabh-chhabra** [comment]
Hi I have uploaded m4a file , this file is sucessfully being replayed on your player provided in APP, but can;t be played or convert to other format outside the app , even in andorid native player its not being played 

[4302389117886.stream.zip](https://github.com/Piasy/RxAndroidAudio/files/4038716/4302389117886.stream.zip)

**Comment by Piasy** [comment]
oh, it's raw PCM, usually you need encode it as mp3 or other format, so that normal media player could play it.

**Comment by saurabh-chhabra** [comment]
ok thanks I am just checking
