### ISSUE TITLE
How to record sound output on speaker

### ISSUE THREAD

**Issue by hungcuiga1** [Piasy/RxAndroidAudio#72]
Hello Piasy, Thank you for great project. My problem is, i want to record sound from a app example: when i watch youtube(tiktok,chrome,...) i want to record soud of apps (it looks like all the sound is playing on the speaker). Does your project do this? Thank you!

**Comment by Piasy** [comment]
This project can't record the content of speaker perfectly, although when you turn up the speaker volume, the voice could be captured, but I don't think that's what you want.
