### ISSUE TITLE
Expose media player *feature*

### ISSUE THREAD

**Issue by lucas34** [Piasy/RxAndroidAudio#9]
Hi,

RxAudioAndroid provide a method to get the progress but not to get the total duration of the media. I know you can also play stream which may not have duration (?). 

I suggest to either create a method to get the total duration or expose the media player which can provide more flexibility for doing things outside the box. 

If you agree, I can PR.

Cheers.

**Comment by Piasy** [comment]
@lucas34 Expose the media player seems not bad, but why do you close it?

**Comment by lucas34** [comment]
I'm actually facing some issue by getting the duration from the media player and find a work around. The server actually send me the duration as well.

I still suggest to expose the media player. Btw, if I PR, are you using the master or the branch 1.2.X ?

**Comment by Piasy** [comment]
1.2.x, the master branch is broken, but I don't have enough time to fix it, sorry about that :(

**Comment by Piasy** [comment]
fixed by #10
